name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: "latest" # Clojure CLI, tools.deps

      - name: Run backend tests
        run: bin/kaocha
